using SharpDX.DirectInput;
using Turbo.Plugins.Default;

namespace Turbo.Plugins.glq
{

    public class GLQ_PluginEnablerOrDisablerPlugin : BasePlugin, ICustomizer
    {

        public GLQ_PluginEnablerOrDisablerPlugin()
        {
            Enabled = true;
        }

        public override void Load(IController hud)
        {
            base.Load(hud);
        }
        public void Customize()
        {
//CustomizeStart
Hud.GetPlugin<BountyTablePlugin>().ToggleKeyEvent = Hud.Input.CreateKeyEvent(true, Key.F10, false, false, false);
Hud.GetPlugin<RiftPlugin>().NephalemRiftPercentEnabled = true;
Hud.GetPlugin<GLQ_MonstersCountPlugin>().yard = 40;
Hud.GetPlugin<GLQ_EliteHealthBarPlugin>().b = 20;
Hud.GetPlugin<GLQ_BannerPlugin>().Enabled = true;
Hud.GetPlugin<StashPreviewPlugin>().Enabled = false;
Hud.GetPlugin<StashUsedSpacePlugin>().Enabled = true;
Hud.GetPlugin<HoveredItemInfoPlugin>().Enabled = true;
Hud.GetPlugin<InventoryKanaiCubedItemsPlugin>().Enabled = true;
Hud.GetPlugin<InventoryMaterialCountPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_AttributeLabelListPlugin>().Enabled = true;
Hud.GetPlugin<GameInfoPlugin>().Enabled = true;
Hud.GetPlugin<MultiplayerExperienceRangePlugin>().Enabled = false;
Hud.GetPlugin<GLQ_DamageBonusPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_NetworkLatencyPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_NotifyAtRiftPercentagePlugin>().Enabled = true;
Hud.GetPlugin<GLQ_BloodShardPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_InventoryFreeSpacePlugin>().Enabled = true;
Hud.GetPlugin<SkillRangeHelperPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_PortraitBottomStatsPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_ResourceOverGlobePlugin>().Enabled = true;
Hud.GetPlugin<GLQ_TopMonsterHealthBarPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_OriginalSkillBarPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_OriginalSkillBarPlugin>().SkillPainter.EnableSkillDpsBar = true;
Hud.GetPlugin<GLQ_CosmeticItemsPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_OtherPlayersPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_HeadStonePlugin>().Enabled = false;
Hud.GetPlugin<GLQ_PlayerSkillPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_PlayersCirclePlugin>().Enabled = false;
Hud.GetPlugin<PickupRangePlugin>().Enabled = false;
Hud.GetPlugin<CheatDeathBuffFeederPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_FollowerPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_PortalPlugin>().Enabled = true;
Hud.GetPlugin<ClickableChestGizmoPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_CursedEventPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_SceneHintPlugin>().Enabled = false;
Hud.GetPlugin<DeadBodyPlugin>().Enabled = false;
Hud.GetPlugin<RackPlugin>().Enabled = true;
Hud.GetPlugin<ChestPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().Enabled = true;
Hud.GetPlugin<GLQ_DoorsPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_GlobePlugin>().Enabled = true;
Hud.GetPlugin<GLQ_HealthGlobePlugin>().Enabled = false;
Hud.GetPlugin<MarkerPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_InventoryAndStashPlugin>().AncientRankEnabled = true;
Hud.GetPlugin<GLQ_InventoryAndStashPlugin>().CanCubedEnabled = false;
Hud.GetPlugin<GLQ_InventoryAndStashPlugin>().HoradricCacheEnabled = true;
Hud.GetPlugin<GLQ_InventoryAndStashPlugin>().SocketedLegendaryGemRankEnabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().Enabled = true;
Hud.GetPlugin<DangerousMonsterPlugin>().Enabled = false;
Hud.GetPlugin<DangerousMonsterPlugin>().AddNames("沙丘梦魇");
Hud.GetPlugin<GLQ_StandardMonsterPlugin>().Enabled = true;
Hud.GetPlugin<MonsterRiftProgressionColoringPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_GoblinPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_MonstersCountPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_EliteHealthBarPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_EliteHealthListPlugin>().Enabled = true;
Hud.GetPlugin<EliteMonsterSkillPlugin>().Enabled = true;
Hud.GetPlugin<ExplosiveMonsterPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_DangerousAffixMonsterPlugin>().SpecialAffix.Add(MonsterAffix.Juggernaut);
Hud.GetPlugin<GLQ_MonsterPackPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_MonsterCirclePlugin>().TrashDecorator.Enabled = false;
Hud.GetPlugin<GLQ_MonsterCirclePlugin>().ChampionDecorator.Enabled = true;
Hud.GetPlugin<GLQ_MonsterCirclePlugin>().RareDecorator.Enabled = true;
Hud.GetPlugin<GLQ_MonsterCirclePlugin>().RareMinionDecorator.Enabled = false;
Hud.GetPlugin<GLQ_MonsterCirclePlugin>().UniqueDecorator.Enabled = true;
Hud.GetPlugin<GLQ_MonsterCirclePlugin>().BossDecorator.Enabled = true;
Hud.GetPlugin<EliteMonsterSkillPlugin>().ArcaneDecorator.Enabled = false;
Hud.GetPlugin<EliteMonsterSkillPlugin>().ArcaneSpawnDecorator.Enabled = true;
Hud.GetPlugin<EliteMonsterSkillPlugin>().DesecratorDecorator.Enabled = true;
Hud.GetPlugin<EliteMonsterSkillPlugin>().FrozenBallDecorator.Enabled = true;
Hud.GetPlugin<EliteMonsterSkillPlugin>().FrozenPulseDecorator.Enabled = true;
Hud.GetPlugin<EliteMonsterSkillPlugin>().MoltenExplosionDecorator.Enabled = true;
Hud.GetPlugin<EliteMonsterSkillPlugin>().MoltenDecorator.Enabled = false;
Hud.GetPlugin<EliteMonsterSkillPlugin>().PlaguedDecorator.Enabled = false;
Hud.GetPlugin<EliteMonsterSkillPlugin>().ThunderstormDecorator.Enabled = false;
Hud.GetPlugin<EliteMonsterSkillPlugin>().GhomDecorator.Enabled = false;
Hud.GetPlugin<GLQ_ShockTowerPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_PetCirclePlugin>().HydraTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PlayerSkillPlugin>().BlackHole = true;
Hud.GetPlugin<GLQ_PlayerSkillPlugin>().Sentry = true;
Hud.GetPlugin<GLQ_PlayerSkillPlugin>().Piranhas = true;
Hud.GetPlugin<GLQ_PlayerSkillPlugin>().SpiritWalkTimer = true;
Hud.GetPlugin<GLQ_PlayerSkillPlugin>().BigBadVoodoo = true;
Hud.GetPlugin<GLQ_PlayerSkillPlugin>().InnerSanctuary = true;
Hud.GetPlugin<MiniMapLeftBuffListPlugin>().Enabled = true;
Hud.GetPlugin<MiniMapRightBuffListPlugin>().Enabled = true;
Hud.GetPlugin<PlayerBottomBuffListPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_ConventionOfElementsBuffListPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_PlayerSkillCirclesPlugin>().SkillRadius.Add(Hud.Render.CreateBrush(255, 255, 0, 0, 3), 15f, 105963, 4);
Hud.GetPlugin<GLQ_PlayerSkillCirclesPlugin>().SkillRadius.Add(Hud.Render.CreateBrush(255, 255,255,255, 3), 50f, 79528, 2);
Hud.GetPlugin<GLQ_TalRashaPlugin>().ShowRashaElements = false;
Hud.GetPlugin<OriginalHealthPotionSkillPlugin>().Enabled = true;
Hud.GetPlugin<RiftPlugin>().GreaterRiftPercentEnabled = true;
Hud.GetPlugin<RiftPlugin>().GreaterRiftTimerEnabled = true;
Hud.GetPlugin<GLQ_MonsterRiftProgressionPlugin>().TurnedOn = true;
Hud.GetPlugin<GLQ_NotifyAtRiftPercentagePlugin>().DisplayLimit = 10;
Hud.GetPlugin<GLQ_RiftInfoPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_PartyInspector>().ToggleKeyEvent = Hud.Input.CreateKeyEvent(true, Key.F12, false, false, false);
Hud.GetPlugin<GLQ_ExperienceOverBarPlugin>().Enabled = false;
Hud.GetPlugin<UiHiddenPlayerSkillBarPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_TopExperienceStatistics>().Enabled = true;
Hud.GetPlugin<GLQ_GreaterRiftPylonMarkerPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().LegendaryDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().AncientDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().PrimalDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().SetDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().AncientSetDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().PrimalSetDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().NormalKeepDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().UtilityDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().BookDecorator.Enabled = false;
Hud.GetPlugin<GLQ_ItemsPlugin>().DeathsBreathDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().InArmorySetDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemDropSoundAlertPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_ItemDropSoundAlertPlugin>().Legendary = false;
Hud.GetPlugin<GLQ_ItemDropSoundAlertPlugin>().AncientLegendary = true;
Hud.GetPlugin<GLQ_ItemDropSoundAlertPlugin>().PrimalAncientLegendary = true;
Hud.GetPlugin<GLQ_ItemDropSoundAlertPlugin>().Set = false;
Hud.GetPlugin<GLQ_ItemDropSoundAlertPlugin>().AncientSet = true;
Hud.GetPlugin<GLQ_ItemDropSoundAlertPlugin>().PrimalAncientSet = true;
Hud.GetPlugin<GLQ_MonsterRiftProgressionPlugin>().ToggleKeyEvent = Hud.Input.CreateKeyEvent(true, Key.F5, false, false, false);
Hud.GetPlugin<GLQ_MonsterRiftProgressionPlugin>().DisplayLimit = 0.00;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().TornadoDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().SlowTimeDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().FirePentagramDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().GeyserTethrysDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().SandmonsterTurretDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().RatSwarmDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().FallingRocksDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().MeteorDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().BloodmawDecorator.Enabled = true;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().BruteLeapDecorator.Enabled = true;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().SmolderingPoolDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().BogBearTrapDecorator.Enabled = false;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().GhomTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().TornadoTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().SlowTimeTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().FirePentagramTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().GeyserTethrysTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_DangerousSkillsPlugin>().SandmonsterTurretTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishTimerDecorator.Enabled = false;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishfireShamanTimerDecorator.Enabled = false;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishRangedTimerDecorator.Enabled = false;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CallOfTheAncientsTimerDecorator.Enabled = false;
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Arcane);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Electrified);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Desecrator);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Frozen);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.FireChains);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Orbiter);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Plagued);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Poison);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Reflect);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Thunderstorm);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Jailer);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Mortar);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.MissileDampening);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Horde);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Avenger);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Wormhole);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Vortex);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Teleporter);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Nightmarish);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Knockback);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Illusionist);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.Fast);
Hud.GetPlugin<GLQ_EliteMonsterAffixPlugin>().AffixDecorators.Remove(MonsterAffix.HealthLink);
Hud.GetPlugin<GLQ_PlayerSkillCirclesPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_PetCirclePlugin>().Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishfireShamanDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishRangedDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishMeleeSycophantsDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().ZombieDogDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().GargantuanDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishHexGiantToadDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().TheGrinReaperDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().mysticAllyDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CallOfTheAncientsDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CompanionDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CompanionSpiderDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CompanionRuneEDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CompanionBoarDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CompanionFerretDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CompanionRuneCDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishMeleeSycophantsTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().GargantuanTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishHexTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().FetishHexGiantToadTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_PetCirclePlugin>().TheGrinReaperTimerDecorator.Enabled = true;
Hud.GetPlugin<GLQ_BuffLabelsPlugin>().Labels.Add(new Label(" 神  目 ", 402461, 2, Hud.Render.CreateBrush(100, 255, 255, 50, 0)));
Hud.GetPlugin<GLQ_ShrineNamePlugin>().EnableSpeak = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().EmpoweredShrineDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().EmpoweredSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().EnlightenedShrineDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().EnlightenedSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().FleetingShrineDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().FleetingSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().FortuneShrineDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().FortuneSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().FrenziedShrineDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().FrenziedSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().BlessedShrineDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().BlessedSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().ChannelingPylonDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().ChannelingSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().ConduitPylonDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().ConduitSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().PowerPylonDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().PowerSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().ShieldPylonDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().ShieldSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().SpeedPylonDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().SpeedSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().BanditShrineDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().BanditSpeak = "默认";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().HealingWellDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().HealingSpeak = "";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().PoolOfReflectionDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().PoolSpeak = "";
Hud.GetPlugin<GLQ_ShrineNamePlugin>().PossibleRiftPylonDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ShrineNamePlugin>().PossibleRiftPylonSpeak = "";
Hud.GetPlugin<GLQ_WeaponDamageRerollCalculatorPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_DifficultiesInfoPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_ConventionOfElementsBuffListPlugin>().OtherScreenPaint = false;
Hud.GetPlugin<GLQ_ConventionOfElementsBuffListPlugin>().OtherPortraitPaint = true;
Hud.GetPlugin<GLQ_ConventionOfElementsBuffListPlugin>().MePortraitPaint = true;
Hud.GetPlugin<GLQ_ConventionOfElementsBuffListPlugin>().MeScreenPaint = false;
Hud.GetPlugin<GLQ_PartyBuffPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_PartyBuffPlugin>().MeScreenPaint = false;
Hud.GetPlugin<GLQ_PartyBuffPlugin>().MePortraitPaint = true;
Hud.GetPlugin<GLQ_PartyBuffPlugin>().OtherScreenPaint = false;
Hud.GetPlugin<GLQ_PartyBuffPlugin>().OtherPortraitPaint = true;
Hud.GetPlugin<GLQ_LegendGemCirclePlugin>().Enabled = true;
Hud.GetPlugin<GLQ_LegendGemCirclePlugin>().ZeiDecorator.Enabled = false;
Hud.GetPlugin<GLQ_LegendGemCirclePlugin>().PainDecorator.Enabled = false;
Hud.GetPlugin<GLQ_LegendGemCirclePlugin>().BaneoftheTrappedDecorator.Enabled = false;
Hud.GetPlugin<GLQ_GlobePlugin>().EnableSpeak = true;
Hud.GetPlugin<GLQ_BannerPlugin>().EnableSpeak = true;
Hud.GetPlugin<GLQ_CosmeticItemsPlugin>().EnableSpeak = true;
Hud.GetPlugin<GLQ_ZeiCircleForBoss>().Enabled = true;
Hud.GetPlugin<GLQ_AncientParthanCount>().Enabled = true;
Hud.GetPlugin<GLQ_AncientParthanCount>().percent = 12;
Hud.GetPlugin<GLQ_BloodShardPlugin>().ShowRemaining = false;
Hud.GetPlugin<GLQ_RedDoorMarker>().Enabled = true;
Hud.GetPlugin<GLQ_NecDeadBodyPlugin>().DeadBodyCount = true;
Hud.GetPlugin<GLQ_NecDeadBodyPlugin>().DeadBodyCircle = true;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().ShowLabel = true;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().ShowCircle = true;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().ShowMark = true;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().ShowProgression = true;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().Distance = 10;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().DisplayLimit = 5;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().MaxRadius = 15;
Hud.GetPlugin<GLQ_MonsterDensityPlugin>().ping = 333;
Hud.GetPlugin<GLQ_DangerousAffixMonsterPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_MonsterDensityAroundCursorPlugin>().Enabled = false;
Hud.GetPlugin<GLQ_MonsterDensityAroundCursorPlugin>().DrawCursorCircle = true;
Hud.GetPlugin<GLQ_MonsterDensityAroundCursorPlugin>().DrawCursorLabel = true;
Hud.GetPlugin<GLQ_MonsterDensityAroundCursorPlugin>().DrawCursorLine = true;
Hud.GetPlugin<GLQ_MonsterDensityAroundCursorPlugin>().OnlyInTown = true;
Hud.GetPlugin<GLQ_MonsterDensityAroundCursorPlugin>().Distance = 15;
Hud.GetPlugin<GLQ_PetCirclePlugin>().CommandSkeletonsDecorator.Enabled = false;
Hud.GetPlugin<GLQ_PetCirclePlugin>().GolemDecorator.Enabled = false;
Hud.GetPlugin<GLQ_PetCirclePlugin>().SkeletonMageDecorator.Enabled = false;
Hud.GetPlugin<GLQ_PetCirclePlugin>().ReviveDecorator.Enabled = false;
Hud.GetPlugin<GLQ_BuffLabelsPlugin>().Labels.Add(new Label("金 轮 阵", 317076, 1, Hud.Render.CreateBrush(100, 255, 255, 0, 0)));
Hud.GetPlugin<GLQ_PlayerSkillBarPlugin>().Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().AddSocketsDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemsPlugin>().BountyCacheDecorator.Enabled = true;
Hud.GetPlugin<GLQ_ItemDropSoundAlertPlugin>().BountyCache = true;
Hud.GetPlugin<GLQ_DirectionLinesPlugin>().Enabled = false;//CustomizeEnd
        }

    }

}